package comp3011.assignment1.model;

/**
 * Internal, provider-neutral result of a speech-to-text conversion.
 *
 * Deliberately decoupled from any vendor response shape so that the Cloud STT provider can be
 * swapped, or replaced by a stub during testing, without changing any caller.
 *
 * @param text         the transcribed text
 * @param inputTokens  input tokens billed for the request
 * @param outputTokens output tokens generated by the model
 */
public record TranscriptionResult(String text, long inputTokens, long outputTokens) {
}
